ALTER TABLE "befe_profiles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_answers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_couples" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_invitations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_personality_reports" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "befe_coupons" ENABLE ROW LEVEL SECURITY;
